# config/packages/rate_limiter.yaml
framework:
  rate_limiter:
    anonymous_api:
      # use 'sliding_window' if you prefer that policy
      policy: 'fixed_window'
      limit: 1000
      interval: '1 minutes'
#      cache_pool: 'cache.anonymous_rate_limiter'
    authenticated_api:
      policy: 'token_bucket'
      limit: 5000
      rate: { interval: '15 minutes', amount: 500 }